export const theme = {
  defaultTheme: {
    SITE_TITLE_COLOR: '#000',
    SITE_TITLE_FONT_SIZE: '',
    SITE_DESCRIPTION_COLOR: '#000',
    SITE_DESCRIPTION_FONT_SIZE: '',
    LINK_COLOR: '#000',
    LINK_FONT_SIZE: '',
    LINK_BORDER_STYLE: '2px dotted #1bbac6',
    LINK_BORDER_HOVER: '2px dotted #d99852',
    LINK_DESCRIPTION_COLOR: '#000',
    LINK_DESCRIPTION_FONT_SIZE: '',
    LINK_DATE_COLOR: '#000',
    LINK_DATE_FONT_SIZE: '',
    TEXT_COLOR: '#000',
    POPUP_BACKGROUND: `radial-gradient(ellipse at top, #1bbac6, transparent),
    radial-gradient(ellipse at bottom, #d99852, transparent)`,
    POPUP_LINK_COLOR: '#000',
    LINKBACK_COLOR: '#fff',
    LINKBACK_LINK_COLOR: 'rgba(129, 209, 209, 1)',
    LINKBACK_LINK_TRANS: 'all 3s ease',
    LINKBACK_LINK_HOVER: 'rgba(234, 222, 200, 1)',
    LINKBACK_BG: '#000',
    INPUT_PADDING: '10px',
    INPUT_INITIAL_BORDER: 'none',
    INPUT_BORDER_LEFT: '1px solid black',
    TEXT_DECORATION: 'none'
  },
  plainTheme: {
    LINK_COLOR: 'auto',
    TEXT_COLOR: '#000',
    LINK_BORDER_STYLE: 'auto',
    LINK_BORDER_HOVER: 'auto',
    POPUP_BACKGROUND: 'none',
    POPUP_LINK_COLOR: 'auto',
    LINKBACK_COLOR: 'auto',
    LINKBACK_LINK_COLOR: 'auto',
    LINKBACK_LINK_TRANS: 'none',
    LINKBACK_LINK_HOVER: 'auto',
    LINKBACK_BG: '#fff',
    INPUT_PADDING: 'auto',
    INPUT_INITIAL_BORDER: 'auto',
    INPUT_BORDER_LEFT: 'auto',
    TEXT_DECORATION: 'auto'
  }
};
